name: BlockFinder
main: com.otacon94.blockfinder.BlockFinder
version: 1.0
author: Otacon94
website: https://github.com/otacon94/blockfinder
softdepend: [CoreProtect]
commands:
 findblock:
    description: BlockFinder. For help type /findblock help
    aliases: [fb]